### ISSUE TITLE
After merging down changes, IEMod crashes on startup

### ISSUE THREAD

**Issue by tjayharvey** [GregRos/IEMod.pw#10]
Here's the message from the log: "Going to try to deserialize PlayerPref SelectionCircleWidth as XML". It looks like this is a nullable float and the serialization code doesn't know what to do with it. Not sure how to fix this, so I'm just commenting out all reference to it in my current environment so I can get it running again.

Edit: This is actually more of a "really long hang". If you let it run for 5 minutes it eventually reaches the main menu, but obviously still an issue.

**Comment by GregRos** [comment]
That is really really weird. Yeah it's definitely an issue. I thought I fixed that was part of the commits. Can you post your `output_log.txt`?

**Comment by GregRos** [comment]
Doh. Sorry about that. Dunno what's wrong with me. I didn't commit the change. I got used to working alone lol. BTW if there is a bad exception, unity will just try to run the code that caused it again and again, until it finally gives up. When there is a long hang it's almost always because of this.

**Comment by GregRos** [comment]
Okay. Now it should work. The error was caused by a `float?` field in the options class. I didn't really fix it, just suppressed the error. 

Also, you should have a `Customize UI` button now. It should work for most things. You have to enable it in the options menu first though.

**Comment by tjayharvey** [comment]
I'll give it a try in a bit. I'm still trying to figure out how to do the merge down without breaking a zillion things. When I try to pull, the system always sees the Patchwork submodule as checked out and won't let me, even if I check it in or undo it. Last time I had to copy my repository elsewhere, blow it away, and start over (which involves 5 minutes of fiddling with the solution to get it to build again, etc). I also have to figure out how to deal with the solution/project files since I'm using Mono.Cecil through NuGet instead of actually attached to the solution (so I have a bunch of extra references that would just break stuff for you if I checked them in). I've been looking into making git just ignore those files, but it looks like doing so would remove them from the GitHub repository, which is obviously not what I want either. Am I missing something obvious here?

May take me a bit to get up to speed on how to do the source control effectively.

**Comment by GregRos** [comment]
It's alright. Yeah, that was me at first. I had to do the copying thing too lol.

It's not possible to ignore the project files/solution files. If you do that, adding new files to the project/solution will not work.

Is there any special reason to use Mono.Cecil through NuGet? I know it's more convenient in a way, but Mono.Cecil has very uninformative exceptions and no real documentation. The reason I downloaded the source itself is because debugging was hell otherwise.

**Comment by tjayharvey** [comment]
The Patchwork project contains references to some files that do not exist in the appropriate folder (so it doesn't build). I believe they should be in Patchwork/cecil-0.9.6/symbols/pdb - at least that's where the solution/project files think they should be. Downloading the Mono.Cecil source and replacing the Patchwork version gives me issues with not having Silverlight installed. I guess I could try replacing just the missing source code files with ones from the Mono source. Or could you add them to the Patchwork repo on your end?

In the meantime, I just have hidden files on and have been including new stuff on my side. There's only so far you can go with that, however.

**Comment by GregRos** [comment]
Yeah they're being ignored for some reason. I'll check why.

That silverlight crap is because of the build configuration of the projects Mono.Cecil projects BTW. You have to set it to .net45. Someone in the cecil repo just left it on Silverlight.

HAHAHA it's because the `.gitignore` file that says which files to ignore is set to ignore `*.pdb`. And the folder name happens to end with `.pdb`.

**Comment by GregRos** [comment]
Okay. I didn't find the ignore file that caused the folders to be ignored. It wasn't the default ignore files. I changed the names of the folders. The files should be available now.

**Comment by tjayharvey** [comment]
Yep, I see the files now. Reverted all my project/solution files and it all works fine now. I also had to use the git command line to update the Patchwork submodule - I think it was out of sync because I had cloned it from the head of Patchwork instead of letting git pick up the submodule. Seems to be pulling better now.

Retested the issue and it is indeed fixed. Closing issue.
