### ISSUE TITLE
Toggle Walk Key Binding Seems To Be Gone

### ISSUE THREAD

**Issue by tjayharvey** [GregRos/IEMod.pw#17]
When trying to test how Toggle Walk and Fast Sneak interact, I was unable to find how to bind a key to Toggle Walk. It's possible Obsidian eliminated the deprecated open Chant UI key binding. Not sure what to do with this.

**Comment by GregRos** [comment]
<s>I think that might be what happened, considering the refactoring/general cleanup they did.

I think we might be able to insert a new key binding. I vote to leave it for later.</s>

Actually, it's may be because I misfiled the toggle walking thing under different mods while organizing it ages ago (in particular, some of it is under NoEnagement, another part under sneaking). I'll try to straighten it out.

**Comment by GregRos** [comment]
The Toggle Walking thing will have to be mostly rewritten, it looks like. Could you do it?

A lot of the code was previously misfiled, but I put it into its own folder in 33f67db0d2b994e273ec4961ecc275debe540406. Some bits are commented out because they don't compile, why others will have to be checked for correctness.

**Comment by tjayharvey** [comment]
I'll take a crack at it. Not 100% sure how keybindings work in Unity, but I imagine I can figure it out with some poking around.

**Comment by tjayharvey** [comment]
I've partially got this figured out (except for giving the control an appropriate label. It just shows up now as _Missing gui - I_).

However, we need to figure out a good way to deal with sections of code that the mods want to share. For instance, both FastSneak and ToggleWalkingMode want to play with the section that calculates movement speed. Multiple mods may want to catch additional key inputs (though currently only ToggleWalkingMode wants to). 

For the key binding/input loop, I'd suggest we make a generic key binder/dispatcher that adds on to the existing input loop and that other mods can register with.

I'm less sure what to do with the movement speed calculation. It may be only those two mods that want to change it (in which case maybe just merge those two mods? After all, they are both about walking and running under unexpected scenarios).

**Comment by GregRos** [comment]
I totally agree. Another thing different mods want to share is the `OnLevelLoad.mod_GameState.FinalizeLevelLoad`, since this is the stuff that happens after a level is loaded (already, 3 mods want to use it, if not more). In this case, the solution is simple; we just inject a new event (more than one?) and let anyone subscribe to it. We could make a list of such things.

However, I really think we should do these changes after we're done porting to 2.0, and have something stable to build on. Otherwise, we won't know what bug is caused by our new additions, and what by the original not working correctly. 

As of right now, there aren't that many mods that depend on the same thing, so we can still refactor everything later on.

### About the labels

Controls with those kinds of labels usually have a label property of type `GUIDatabaseString` or something similar (could be a superclass as well). That's an entry in the string table. Just find the property, and set it to `IEModString.Register("Your Label")`. The IEModString takes care of everything.

Alternatively, you could try to find a property like `FormatString`, which just accepts a string. You may need to dump the object-component structure of the control to file, to find the right component/child with the property. You can use one of the `UnityPrinter`s to do so.

**Comment by tjayharvey** [comment]
Actually there's a function in the same class that's responsible for sorting the controls into sections that handles retrieving the text. So I could simply override that (what I've currently done - just forces a return of "Toggle Walk Mode" for that control type) or modify the data structure that backs it (which is just an array of GUIDatabaseString). I'm probably just going to leave it as-is for now, and it works okay now.

Later on, I will want to investigate if there's some way we can take advantage of the localization files (by either adding our own IEMod.stringtable or adding on to an existing one if this isn't possible), which will probably require using GUIDatabaseString. But English-only should be sufficient for the first release.

**Comment by tjayharvey** [comment]
Fix checked in and in existing pull request. Will open new issues later for longer-term restructuring.
