### ISSUE TITLE
Max adventurers count.

### ISSUE THREAD

**Issue by tariel36** [GregRos/IEMod.pw#49]
Is it possible to add an option to set the maximum adventurers you can hire in tavern? For now it's 8 adventurers. I managed to find the readonly variable that holds this value in Assembly-CSharp.dll. I would gladly change it myself but can't get IEMod to build (so many errors about versions).

Exact location is:
Assembly-CSharp.dll, PartyMemberAI class (PartyMemberAI.cs file), line around 67:
public static readonly int MaxAdventurers = 8;

**Comment by GregRos** [comment]
What kind of errors? I'd really love to help you get it working :) Then you can do it in exactly the way you want, and submit a pull request and I'll integrate it as part of the repo. Or you could change other things. 

Also, if there are problems, I'd like to fix them.

If that's the only place where it's specified, you should be able to do it easily.

There is a guide to building it in the main page, and also you can see #39, the problems that bigtuna had in building, and how they were resolved.

**Comment by tariel36** [comment]
Alright, today the errors are gone (I think the reason behind those was already patched Assembly-CSharp.dll, since I restored that file from steam today morning).

For now I build on Debug configuration. I Mean I built the PrepareEnviornment on debug, ran, that worked fine. Then built the _Start! on debug and that worked too. However there are 2 errors in Start.exe console:

1.
`Conflict  between types: <PrivateImplementationDetails>, and <PrivateImplementationDetails>.`
`Failed to create member.`
`Since this is an implicitly created type, new members will be added to the existing type Hopefuly, there will be no collisions.`

2.
~~`Conflict between fileds: Boolean mod_Health::<m_isAnimalCompanion>l__BackingField, and Boolean Health::<m_isAnimalCompanion>k__BackingField.`
`Failed to create member.`~~
(This one is gone now after downloading `a508a6c294958ca3d19e28545b3e73bb39031406` commit)

I'm not sure if this is fine.

I've got plently of different build configurations. Which one should I use for release and debug builds?

Also I'm not sure about 5th point in Building instruction:
`5. Make sure the iemod (the lowercase one!) folder is installed at PillarsOfEternity_Data/Managed.`
Should I add this myself or IEMod should install itself here after i run _Start! ?

There are few warnnings that may be interesting but I'm not sure if they come from wrong build configuration so I'll post them later :)

@edit fixed formatting..

**Comment by tariel36** [comment]
I've run into 2 issues during making my mod.
I dont really know if I can modify `static readonly field` (atleast my code didn't work).
So I modded the calculation method for actual hiring (this worked), but the field is also used in warning message `"You cant hire more than " + MaxAdventurers + " adventurers"`, so this would show wrong message when player encounters this warnning. Any tips for such thing?

@edit
I probably should show why is this a issue, the actual messagebox call:
`UIWindowManager.ShowMessageBox(UIMessageBox.ButtonStyle.OK, string.Empty, GUIUtils.Format(0x761, parameters));`
What worries me is `GUIUtils.Format` call.

**Comment by GregRos** [comment]
## The errors

The first error isn't really an error, it's more like a warning. Like the description says, hopefully nothing will go wrong.

The second one is a silly annoying thing I fixed (it wasn't important, just distracting).

## The readonly field

@tariel36 If you like, you can hold off until tomorrow or later today (when I find time), and I'll add a feature to Patchwork that lets you modify attributes like `readonly` and remove them. It's well overdue anyway.

I don't quite understand about the message box thing. Can't you just copy the contents of the method, and remove the call?

Using Telerik JustDecompile or a similar tool you can just search for all references to `MaxAdventurers` and fix them (if you don't want to wait that is :smiley:).

## Edit

Okay, I did it. Here is how it works in your case:

```
[ToggleFieldAttributes(FieldAttributes.InitOnly)]
[ModifiesMember(nameof(MaxAdventurers))]
public static int mod_MaxAdventurers;
```

The `FieldAttributes` enum refers to declaration attributes like `readonly` and `virtual`. It has nothing to do with the attributes like `[Description]` and so on. 

The attribute `[ToggleFieldAttributes]` toggles the flags you give it. For example, the above usage toggles the `InitOnly` flag which in C# is called `readonly`. There is also `[ToggleMethodAttributes]` for methods, that you can use to toggle `virtual` and `sealed` for example. There isn't one for types, mainly because that would involve more changes in the code, and I just wanted to release this ASAP, and also more changes in the code means it would be harder to merge it with a big update I'm working on (which isn't ready for release).

You must use `[ToggleFieldAttributes]` with the `[ModifiesMember]` attribute, to tell it what member to patch. Also, note that by default, this attribute updates accessibility, so the following would probably cause errors:

```
[ToggleFieldAttributes(FieldAttributes.InitOnly)]
[ModifiesMember(nameof(MaxAdventurers))]
private static int mod_MaxAdventurers;
```

**Comment by tariel36** [comment]
Thank you for your reply. I'm going to check it out in following days when I have some time. If you could specify which build configuration should I use for release it would be great.

![2](https://cloud.githubusercontent.com/assets/2964246/9720005/38f175bc-558a-11e5-913c-c83463e02575.png)

The last 2 (not visible) on the list are windows phone configurations.

**Comment by GregRos** [comment]
Wow. That's really confusing. You should just use `Debug`. I'll clean up the solution and project files, removing all the unnecessary configurations. Thanks for pointing it out. 

Are you planning to release it separately, or incorporate it into IE Mod? If the latter, just submit a pull request and I'll integrate it.

**Comment by tariel36** [comment]
I would love to incorporate it into IE Mod. When I get it done (need some time to make sure its done and during week it's hard for me to spare some :() I'll submit pull request.
