### ISSUE TITLE
Soulbound Levelling // New Methods to be Used Outside Class in Patchwork

### ISSUE THREAD

**Issue by tjayharvey** [GregRos/IEMod.pw#53]
I saw we have a request to add a way to level soulbound weapons. It seems like this should be straightforward to do as a console command, but the way that I'd think about doing it seems to have a snag. I can add a method to EquipmentSoulbind to allow me to force it to level. I can add a console command to receive the command. But I don't see any way for the console command to call the new function, because it won't compile. I know the method will be there when Patchwork finishes, but the compiler can't tell that. I can't think of an elegant way to deal with this. I'm actually having trouble thinking of ANY way to do it as a console command.

It's certainly doable as a mod setting simply by overriding the routine that checks for whether we're ready to go up a level and forcing it to say yes. But that's kind of awkward and doesn't give you much control.

Hmm. Random idea: would reflection help? Since the call will work at runtime when the new method has been patched into the source type, by "disguising" the direct call as a reflection-based one, can I get around the compiler's inability to recognize that the method will be there?

**Comment by GregRos** [comment]
To call a new method in a modified type, you need to do the following:

```
EquipmentSoulBind soulbind;
var modSoulbind = (mod_EquipmentSoulBind)soulbind;
//will be turned into: var modSoulbind = (EquipmentSoulBind)soulbind;, e.g. nop really.
modSoulbind.NewMethod();
```

The type `mod_EquipmentSoulBind` will be mapped to `EquipmentSoulBind`. Use it only in method bodies, as I just realized that in signatures it will lead to errors (never did this, so I never encountered this issue). This issue will be fixed sometime in the coming days (as a consequence of other work).

I'll add it to the documentation, since I just realized it's really not obvious lol. 

It's not the best system in the world, so if you have any better ideas, let me know.

Reflection would also work. As would a `dynamic` call (if we had the framework support).

**Comment by tjayharvey** [comment]
It definitely works via Reflection (I used it to test out the different soulbound weapons last night). I'll try the other mechanism tonight. Right now it only works on equipped soulbound weapons, but that's just because I haven't yet figured out how to iterate over the character's inventory.

**Comment by tjayharvey** [comment]
Confirmed this worked. I have this task done, but I'm working in a branch now on a generic framework for modifying abilities, so it may be a bit before it's ready for merge.

**Comment by GregRos** [comment]
Sweet :smile: I hope it works out. Ability modification would be amazing.

**Comment by tjayharvey** [comment]
New Command is 'UnlockSoulbound Companion_Eder(Clone)_0' (or whatever player the weapon is bound to). The weapon must be already soulbound and currently equipped and selected as the character's weapon.

I'll see about making it smart enough to find soulbound items elsewhere in inventory at a later date.
