### ISSUE TITLE
Weird Returning Storm targeting issue (original 2.01)

### ISSUE THREAD

**Issue by GregRos** [GregRos/IEMod.pw#57]
When I try to cast Returning Storm or a similar effect, the targeting is really glitchy and kind of flashes on and off. Is it something that you experience as well? 

This happens both with and without IE Mod. (though of course without IE Mod, returning storm does not work at all)

**Comment by tjayharvey** [comment]
As in it doesn't hit people? Or in terms of how it looks when you try to cast the spell?

I get a normal targeting area when I try to cast it. And it seems to hit things as expected (i.e. the enemies). I don't think I have any of the target mods turned on at this point.

The only thing I noticed that seemed a bit odd is that I had a bunch of commands queued that the druid didn't execute after (like turning into a cat and going and beating on people's faces). I think that might have been because I had another spell queued first (not sure if it's intended to be legal to cast other spells while Returning Storm is still casting - I didn't have a druid in my pre 2.0 playthroughs.

**Comment by GregRos** [comment]
Nah, I guess it only happens for me. If you experienced it, you'd know what I mean. It's just a visual glitch. 

I corrupted my save in a subtle way ages ago while playing around, and sometimes I get weird glitches, so it's hard to know what's my fault and what isn't.

**Comment by tjayharvey** [comment]
Ah. Yes, I have one playthrough started after 2.0 and started another one after 2.01 (mostly because I decided I wanted to build my team a little differently after reaching Defiance Bay). Seems to work okay for both.
