### ISSUE TITLE
Errors when running _start

### ISSUE THREAD

**Issue by Archey6** [GregRos/IEMod.pw#69]
I've followed the build instructions to the letter, everything works dandy up until i try to run _Start! This is one of the errors I'm getting 

> 'UIDropdownMenu' does not contain a definition for 'Background' and no extension method 'Background' accepting a first argument of type 'UIDropdownMenu' could be found 

Here is an image of the others: http://imgur.com/uscuYZt Most are similar to the one i posted, but there is also one about mod_GameState

> mod_GameState' does not contain a definition for 'CouldCampOnLastMap' and no extension method 'CouldCampOnLastMap' accepting a first argument of type 'mod_GameState' could be found 

I think I'm missing a dependency or two, but I'm not sure which ones. Any help is appreciated

**Comment by tjayharvey** [comment]
The entire structure has changed now that we're using a launcher, but roughly speaking this was due to not updating the PoE reference to the current version. Basically, IEMod compiles with an understanding of how the current PoE works based on that reference DLL. It then applies changes to the game's DLL. If the version used as a reference and the one that's actually targeting for modded have differences, you get stuff like this. In this case, the base GameState object used to have a method CouldCampOnLastMap, and Obsidian has eliminated it in their latest patch (almost certainly due to refactor). Thus, Patchwork cannot resolve the reference to it. If the version IEMod is referencing was up to date, the compiler would notice that it isn't a valid reference and give you more helpful error info (like the line number to fix).
