### ISSUE TITLE
Any chances for version working with 3.03 Beta?

### ISSUE THREAD

**Issue by ALIENQuake** [GregRos/IEMod.pw#92]
Hi, Any chances for version working with 3.03 Beta?

**Comment by Alakabon** [comment]
I was going to wait for the actual 3.03 release to get started but I guess
I can look into it a bit sooner.

**Comment by ALIENQuake** [comment]
I would be very grateful even if it would be just recompilation using game dll's from newest version. I've trying to compile it by myself but I got errors: https://github.com/IEMod/IEMod.pw/issues/39#issuecomment-230161407

**Comment by Alakabon** [comment]
Allright, I got it to compile and run with the patchwork launcher using the lastest fork from Llerelol, found here:
https://github.com/llerelol/IEMod.pw

You probably forgot to update the assembly with OAC ( More on that here from tjayharvey: https://github.com/IEMod/IEMod.pw/issues/72)

I only tested fastsneak because I have no save files and I don't have time to play tonight but it seems to work just fine.

THIS IS NOT A RELEASE VERSION, and try it at your own risk, make sure you don't mind losing the save file if anything goes wrong. It is the same exact mod as 3.02 for the moment, so you may experience some crashing... I never did and even with saves from people who crashed I could not replicate it... I have no idea how to fix that but I'll keep looking into it for the future.

I'll attach a zip to this with the latest IEMod.pw.dll
[IEMod.pw.dll.zip](https://github.com/IEMod/IEMod.pw/files/345464/IEMod.pw.dll.zip)

In order to make it run, you will need to ''re-apply it'' with patchwork, meaning you cannot just swap the files, you have to manually remove it from the patchwork active menu and then add it again.

I'll probably make a better guide and things once everything is stable again, but if you are in a hurry IN THEORY this should work.

**Comment by ALIENQuake** [comment]
Don't worry, I'm aware that it is "use at your own risk" version. Thank you very much!

**Comment by llerelol** [comment]
I also planned to update it when 3.03 release hits. Planning to do another playthrough fairly soon. Hey Alakabon, did you by any chance figured what caused game to crash in combat? I have failed miserably last time i tried to fix that thing.

**Comment by llerelol** [comment]
Yea, also if you're interested i have a save game that crashes my game 99% of times. Can share if you wanna take a look.

**Comment by Alakabon** [comment]
I couldn't find the cause either... It even crashes when no options are on apparently, so it's probably not in the modules themselves. This means something is broken a bit deeper inside.

From what I've read you had better success with several individual modules? It seems people are mostly interested in XP/FastSneak/NPC stats and console commands. 

It might be a better idea going forward to release each component seperatly and allow people to select only the ones they would have toggled. From what I understand about Patchwork you can load a few of them at the same time as long as they modify different methods, which is mostly the case anyway.

That being said, I'll take a look at the save if you still have it around.

**Comment by llerelol** [comment]
i sent you a letter on nexus.

**Comment by Alakabon** [comment]
So I remade a few modules last night and it turns out Console Commands might be the problem. When applying it with patchwork it generates a few errors. It makes sense too given that the crash happens even when everything is toggled off. I'm pretty sure it's the only thing that's loaded every time. I was too tired to figure it out last night but I'll start looking a bit more that way soon.

I also figured out a way to make spells per encounter again,there was a demand for that at some point.

**Comment by Alakabon** [comment]
I found the actual problem method override (MethodIsAvailable).I have no idea why it doesnt work, it makes perfect sense and everything looks in order to me... 

That being said I changed the override to RunCommand instead and it's compiling and being applied without any errors.

I could use some help with the testing, if you guys still have problematic saves. Here's the dll:
[IEMod.pw.dll.zip](https://github.com/IEMod/IEMod.pw/files/355481/IEMod.pw.dll.zip)

Edit: From my testing it seems to have fixed it... Who would have thought. I guess there's no more reason to use separate modules now.

**Comment by Devildream** [comment]
Hey Alakabon, any chance of the autosave feature being looked at? No idea how complex it is of course. Would it be possible to disable it manually somehow? Thanks.

Just FYI im 90 hours in on this run through with your 3.03 dll and ive had only 2 crashes in combat, both of which worked fine on reload.

**Comment by Alakabon** [comment]
Yeah I tweaked a thing or two, testing right now... Sorry for the delay it's been a long week.

Edit: Should work now, I've uploaded the new DLL to the nexus.

**Comment by Devildream** [comment]
God send once again, just hit act 3 which is pretty bad for running around, autosave features seem to be working perfectly. So much less of a chore now. Baffles me why they set it up like that especially later in the game when the saves are big. Anyways thanks for the work on this buddy, saved me headaches. just wish id of checked back here sooner!
