### ISSUE TITLE
Current Linux support?

### ISSUE THREAD

**Issue by mwiens91** [GregRos/IEMod.pw#99]
Not sure if this is still being maintained but I notice that on [Nexus Mods](https://www.nexusmods.com/pillarsofeternity/mods/1/) the installation instructions are specifically for Windows. I haven't looked into the code at all, but am wondering if setting this up on a Linux PoE installation would be a lot of hastle, or if anyone has experience doing so.

This mod looks great and fixes many complaints I have with this otherwise fantastic game :+1:

**Comment by GregRos** [comment]
@mwiens91 I wrote the Patchwork Launcher to work with Linux, and I'm pretty sure it's still used in the mod (which is really surprising, actually!). You need to install Mono to get it to work and then start with executable with `mono PatchworkLauncher.exe`. The UI will look dated (it's Windows Forms, what can I say) but it should work.

It doesn't work on OSX mainly because it was too much of a hassle to get a VM with OSX on it to test it out there. I tried for a while though.

Good luck :smile:

**Comment by mwiens91** [comment]
Perfect. Got it working. Thanks for the tip on using `mono` with the Patchwork Launcher executable.
